name: "One Wokflow - Infrastructure "

on:
  workflow_dispatch:
    inputs: 
      env_type: 
        default: dev
        description: "Please, choose one of the options for environment [dev, test, production]"
      secname:
      
env:
      DEPLOY_ENV: 'sbx'
      CONCAT_TEST: Raj${{ github.event.inputs.secname }}
jobs: 

  SetupInfra: 
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env_type }}
    steps: 
    - name: Set the env variables according to env
      run: |
        TEST_SEC=${{ secrets.SEC_NAME }}
        echo "TEST_SEC_NAME=${TEST_SEC}" >> $GITHUB_ENV
        echo "${{ secrets.TEST_SEC }}"
        echo $TEST_SEC_NAME
        
    - run: echo "It is Devsec1"
      name: Check dev sec1
      if: $TEST_SEC_NAME == 'devsec'

      
    - run: echo "It is Dev ${{ env.CONCAT_TEST }}"
      name: Setup dev env
      if: github.event.inputs.env_type == 'dev'

    - run: echo "It is test"
      name: Setup test env
      if: github.event.inputs.env_type == 'test'
      
    - run: echo "It is prod"
      name: Set prod env
      if: github.event.inputs.env_type == 'prod'

    - run: echo "It is secdev"
      name: secdev
      if: github.event.inputs.secname == 'secdev'
    
    - run: echo "It is sectest"
      name: sectest
      if: github.event.inputs.secname == 'sectest'
    
    - run: echo "It is secprod"
      name: secprod
      if: github.event.inputs.secname == 'secprod'
      
    - run: echo "It is secrepo"
      name: secrepo
      if: github.event.inputs.secname == 'secrepo'
