
name: "Setup Infrastructure "

on:
  workflow_dispatch:
    inputs: 
      env_type: 
        default: dev
        description: "Please, choose one of the options for environment [dev, test, production]"
      
env:
      DEPLOY_ENV: 'sbx'
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
    - run: echo "It is Dev ${{ secrets.SEC_NAME}}"
      name: Set name1
      if: github.event.inputs.env_type == 'dev'
      
    - run: echo "It is test ${{ secrets.SEC_NAME}}"
      name: Set name2
      if: github.event.inputs.env_type == 'test'
